export default {
  EMPLOYEES: [{
    name: 'Adam',
    lastname: 'Nowak',
    position: 'Frontend developer',
    contractType: 'Student :)',
    phoneNumber: 123456789,
    technologies: ['Javascript', 'Java'],
  },
  {
    name: 'Bartek',
    lastname: 'Kowalski',
    position: 'Backend developer',
    contractType: 'Kontrakt B2B',
    phoneNumber: 123456789,
    technologies: ['Java', 'MySQL'],
  },
  {
    name: 'Zbigniew',
    lastname: 'Polak',
    position: 'DevOps',
    contractType: 'Umowa o prace',
    phoneNumber: 123456789,
    technologies: ['Azure', 'Docker', 'Jenkins'],
  },
  {
    name: 'Marcin',
    lastname: 'Inny',
    position: 'Solution architect',
    contractType: 'Kontrakt B2B',
    phoneNumber: 123456789,
    technologies: ['Node.js', 'AWS'],
  },
  {
    name: 'Łukasz',
    lastname: 'Kochajewski',
    position: 'Backend developer',
    contractType: 'Umowa o prace',
    phoneNumber: 123456789,
    technologies: ['.NET', 'Node.js', 'MongoDB'],
  }],
};
